import { RoleDefinition, RoleId } from '../types/game';

export const ALL_ROLES: Record<RoleId, RoleDefinition> = {
  burger: {
    id: 'burger',
    name: 'Villager',
    dutchName: 'Burger',
    team: 'village',
    icon: '🌾',
    badgeColor: 'bg-amber-600/30 text-amber-300 border-amber-500/40',
    cardBg: 'from-amber-950/90 via-slate-900 to-amber-950/40',
    borderColor: 'border-amber-500/40',
    nightOrder: 0,
    wakesEveryNight: false,
    wakesFirstNightOnly: false,
    description: 'Heeft geen speciale nachtkracht, maar bezit overtuigingskracht en scherpzinnigheid om overdag de weerwolven te ontmaskeren.',
    nightInstruction: 'Slaapt tijdens de nacht.',
    scriptLinesDutch: ['De burgers slapen rustig in hun bedden.'],
    scriptLinesEnglish: ['The villagers sleep soundly.'],
  },
  weerwolf: {
    id: 'weerwolf',
    name: 'Werewolf',
    dutchName: 'Weerwolf',
    team: 'werewolves',
    icon: '🐺',
    badgeColor: 'bg-red-950/70 text-red-400 border-red-500/50',
    cardBg: 'from-red-950/90 via-slate-950 to-red-900/30',
    borderColor: 'border-red-500/50',
    nightOrder: 5,
    wakesEveryNight: true,
    wakesFirstNightOnly: false,
    description: 'Ontwaakt elke nacht samen met de andere weerwolven om in stilte één dorpsbewoner te kiezen die zij verslinden.',
    nightInstruction: 'Weerwolven, word wakker! Kijk elkaar aan en kies in stilte een slachtoffer.',
    scriptLinesDutch: [
      'Weerwolven, open jullie ogen en herken elkaar.',
      'Wijs in stilte een slachtoffer aan dat jullie willen verslinden.',
      'Weerwolven, sluit jullie ogen en ga weer slapen.',
    ],
    scriptLinesEnglish: [
      'Werewolves, open your eyes and recognize one another.',
      'Silently choose a victim to devour.',
      'Werewolves, close your eyes and go back to sleep.',
    ],
  },
  zienster: {
    id: 'zienster',
    name: 'Seer',
    dutchName: 'Zienster',
    team: 'village',
    icon: '🔮',
    badgeColor: 'bg-indigo-950/70 text-indigo-300 border-indigo-500/50',
    cardBg: 'from-indigo-950/90 via-slate-950 to-purple-950/40',
    borderColor: 'border-indigo-500/50',
    nightOrder: 4,
    wakesEveryNight: true,
    wakesFirstNightOnly: false,
    description: 'Mag elke nacht de geheime rol van één speler bekijken via haar magische kristallen bol.',
    nightInstruction: 'Zienster, word wakker! Wijs een speler aan wiens ware identiteit je wilt zien.',
    scriptLinesDutch: [
      'Zienster, ontwaak! Wijs één speler aan.',
      'Ik toon je in het geheim de rol van deze speler.',
      'Zienster, sluit je ogen en slaap weer in.',
    ],
    scriptLinesEnglish: [
      'Seer, wake up! Point to one player.',
      'I will secretly reveal their true role to you.',
      'Seer, close your eyes and sleep.',
    ],
  },
  heks: {
    id: 'heks',
    name: 'Witch',
    dutchName: 'Heks',
    team: 'village',
    icon: '🧙‍♀️',
    badgeColor: 'bg-emerald-950/70 text-emerald-300 border-emerald-500/50',
    cardBg: 'from-emerald-950/90 via-slate-950 to-teal-950/40',
    borderColor: 'border-emerald-500/50',
    nightOrder: 6,
    wakesEveryNight: true,
    wakesFirstNightOnly: false,
    description: 'Beschikt over twee krachtige toverdranken: één Levenselixer om het slachtoffer van de weerwolven te redden, en één Dodelijk Vergif om een willekeurige speler uit te schakelen.',
    nightInstruction: 'Heks, ontwaak! Ik toon je het slachtoffer van de weerwolven. Wil je de levensdrank gebruiken? Of wil je iemand vergiftigen?',
    scriptLinesDutch: [
      'Heks, word wakker! Dit is het slachtoffer van de weerwolven...',
      'Gebruik je je levensdrank om deze speler te redden?',
      'Wil je je vergifdrank gebruiken om iemand anders te doden?',
      'Heks, sluit je ogen en ga weer slapen.',
    ],
    scriptLinesEnglish: [
      'Witch, wake up! This is the victim of the werewolves...',
      'Do you want to use your healing potion to save them?',
      'Do you want to use your poison potion to kill someone else?',
      'Witch, close your eyes and sleep.',
    ],
  },
  jager: {
    id: 'jager',
    name: 'Hunter',
    dutchName: 'Jager',
    team: 'village',
    icon: '🏹',
    badgeColor: 'bg-stone-800 text-stone-300 border-stone-600',
    cardBg: 'from-stone-900 via-slate-900 to-amber-950/40',
    borderColor: 'border-stone-500',
    nightOrder: 0,
    wakesEveryNight: false,
    wakesFirstNightOnly: false,
    description: 'Als de jager sterft (door wolven of dorpsstemming), vuurt hij in zijn doodsstrijd direct een dodelijk schot af op een speler naar keuze!',
    nightInstruction: 'Reageert pas op het moment van overlijden.',
    scriptLinesDutch: [
      'De jager is gestorven! Met zijn laatste adem lost hij een dodelijk schot.',
      'Jager, wijs direct jouw doelwit aan!',
    ],
    scriptLinesEnglish: [
      'The hunter has died! With their dying breath they take a shot.',
      'Hunter, point to your target now!',
    ],
  },
  cupido: {
    id: 'cupido',
    name: 'Cupid',
    dutchName: 'Cupido',
    team: 'village',
    icon: '💘',
    badgeColor: 'bg-rose-950/70 text-rose-300 border-rose-500/50',
    cardBg: 'from-rose-950/90 via-slate-950 to-pink-950/40',
    borderColor: 'border-rose-500/50',
    nightOrder: 2,
    wakesEveryNight: false,
    wakesFirstNightOnly: true,
    description: 'Ontwaakt uitsluitend in de allereerste nacht en wijst twee spelers aan die voor altijd elkaars geliefden worden. Als de een sterft, sterft de ander direct van liefdesverdriet.',
    nightInstruction: 'Cupido, word wakker! Wijs twee dorpsbewoners aan die elkaar eeuwige trouw zweren.',
    scriptLinesDutch: [
      'Cupido, ontwaak! Wijs twee dorpsbewoners aan die elkaars geliefden worden.',
      'Cupido, sluit je ogen en ga weer slapen.',
      'Geliefden, open jullie ogen en herken elkaar!',
      'Geliefden, sluit weer jullie ogen.',
    ],
    scriptLinesEnglish: [
      'Cupid, wake up! Point to two villagers to become lovers.',
      'Cupid, close your eyes.',
      'Lovers, open your eyes and look at each other!',
      'Lovers, close your eyes.',
    ],
  },
  beschermer: {
    id: 'beschermer',
    name: 'Bodyguard / Defender',
    dutchName: 'Beschermer',
    team: 'village',
    icon: '🛡️',
    badgeColor: 'bg-cyan-950/70 text-cyan-300 border-cyan-500/50',
    cardBg: 'from-cyan-950/90 via-slate-950 to-blue-950/40',
    borderColor: 'border-cyan-500/50',
    nightOrder: 3,
    wakesEveryNight: true,
    wakesFirstNightOnly: false,
    description: 'Kiest elke nacht één speler om te beschermen tegen de weerwolven. Mag niet twee nachten achter elkaar dezelfde persoon beschermen.',
    nightInstruction: 'Beschermer, word wakker! Wijs een speler aan die je vannacht wilt verdedigen.',
    scriptLinesDutch: [
      'Beschermer, ontwaak! Wijs één speler aan die je wilt verdedigen.',
      'Beschermer, sluit je ogen en slaap weer in.',
    ],
    scriptLinesEnglish: [
      'Bodyguard, wake up! Point to one player to protect tonight.',
      'Bodyguard, close your eyes.',
    ],
  },
  dief: {
    id: 'dief',
    name: 'Thief',
    dutchName: 'Dief',
    team: 'village',
    icon: '🗡️',
    badgeColor: 'bg-slate-800 text-slate-300 border-slate-600',
    cardBg: 'from-slate-900 via-slate-950 to-slate-900',
    borderColor: 'border-slate-600',
    nightOrder: 1,
    wakesEveryNight: false,
    wakesFirstNightOnly: true,
    description: 'Ontwaakt in de allereerste nacht en mag kiezen uit twee niet-uitgedeelde kaarten om van rol te wisselen.',
    nightInstruction: 'Dief, word wakker! Bekijk de 2 extra kaarten en kies eventueel een nieuwe rol.',
    scriptLinesDutch: [
      'Dief, word wakker! Bekijk de twee overgebleven kaarten.',
      'Kies of je van rol wisselt of burger blijft.',
      'Dief, ga weer slapen.',
    ],
    scriptLinesEnglish: [
      'Thief, wake up! Look at the two extra cards.',
      'Choose whether to switch or stay villager.',
      'Thief, go back to sleep.',
    ],
  },
  dorpsoudste: {
    id: 'dorpsoudste',
    name: 'Elder',
    dutchName: 'Dorpsoudste',
    team: 'village',
    icon: '🧔',
    badgeColor: 'bg-amber-900/60 text-amber-200 border-amber-700',
    cardBg: 'from-amber-950/90 via-slate-950 to-slate-900',
    borderColor: 'border-amber-700',
    nightOrder: 0,
    wakesEveryNight: false,
    wakesFirstNightOnly: false,
    description: 'Overleeft de eerste weerwolvenaanval (heeft 2 levens tegen wolven). Als het dorp hem ophangt, verliezen alle dorpelingen hun speciale krachten!',
    nightInstruction: 'Heeft 2 levens tegen wolven.',
    scriptLinesDutch: ['De dorpsoudste waakt over de tradities.'],
    scriptLinesEnglish: ['The elder protects the village heritage.'],
  },
  meisje: {
    id: 'meisje',
    name: 'Little Girl',
    dutchName: 'Spiedend Meisje',
    team: 'village',
    icon: '👧',
    badgeColor: 'bg-pink-950/70 text-pink-300 border-pink-500/50',
    cardBg: 'from-pink-950/90 via-slate-950 to-rose-950/40',
    borderColor: 'border-pink-500/50',
    nightOrder: 0,
    wakesEveryNight: false,
    wakesFirstNightOnly: false,
    description: 'Mag stiekem gluren terwijl de weerwolven hun ogen openen. Maar pas op: als de weerwolven haar betrappen, is zij het slachtoffer!',
    nightInstruction: 'Mag stiekem spieken tijdens de wolvenfase.',
    scriptLinesDutch: ['Het spiedende meisje mag stiekem spieken.'],
    scriptLinesEnglish: ['The little girl may peek during werewolf turn.'],
  },
  fluitspeler: {
    id: 'fluitspeler',
    name: 'Pied Piper',
    dutchName: 'Fluitspeler',
    team: 'solo',
    icon: '🪈',
    badgeColor: 'bg-violet-950/70 text-violet-300 border-violet-500/50',
    cardBg: 'from-violet-950/90 via-slate-950 to-purple-950/40',
    borderColor: 'border-violet-500/50',
    nightOrder: 7,
    wakesEveryNight: true,
    wakesFirstNightOnly: false,
    description: 'Solo-speler: betovert elke nacht 2 spelers. Wint het spel in zijn eentje zodra alle levende spelers betoverd zijn!',
    nightInstruction: 'Fluitspeler, ontwaak! Wijs 2 spelers aan om te betoveren.',
    scriptLinesDutch: [
      'Fluitspeler, ontwaak! Wijs 2 spelers aan om te betoveren.',
      'Fluitspeler, ga weer slapen.',
      'Alle betoverde spelers, open jullie ogen en herken elkaar!',
      'Betoverde spelers, sluit weer je ogen.',
    ],
    scriptLinesEnglish: [
      'Pied Piper, wake up! Point to 2 players to enchant.',
      'Pied Piper, close your eyes.',
      'All enchanted players, open your eyes and recognize each other!',
      'Enchanted players, close your eyes.',
    ],
  },
  burgemeester: {
    id: 'burgemeester',
    name: 'Mayor Title',
    dutchName: 'Burgemeester (Ambtsketen)',
    team: 'village',
    icon: '👑',
    badgeColor: 'bg-yellow-500/30 text-yellow-200 border-yellow-400/50',
    cardBg: 'from-yellow-950/80 via-slate-950 to-amber-950/40',
    borderColor: 'border-yellow-400/50',
    nightOrder: 0,
    wakesEveryNight: false,
    wakesFirstNightOnly: false,
    description: 'Publieke eretitel die aan ELKE speler kan worden toegekend naast hun geheime rolkaart! De stem van de burgemeester telt dubbel. Wijst bij sterven een opvolger aan.',
    nightInstruction: 'Stem telt dubbel. Wijst opvolger aan bij overlijden.',
    scriptLinesDutch: ['De burgemeester leidt het dorpsdebat.'],
    scriptLinesEnglish: ['The mayor leads the village debate.'],
  },
  onbekend: {
    id: 'onbekend',
    name: 'Unknown / Hidden',
    dutchName: 'Onbekend (Nog Ontdekken)',
    team: 'village',
    icon: '❓',
    badgeColor: 'bg-slate-800 text-slate-300 border-slate-600',
    cardBg: 'from-slate-900 via-slate-950 to-slate-900',
    borderColor: 'border-slate-600',
    nightOrder: 0,
    wakesEveryNight: false,
    wakesFirstNightOnly: false,
    description: 'Rol is nog niet bekend bij de spelleider. Kan tijdens de nachtrondes worden toegewezen zodra het karakter ontwaakt!',
    nightInstruction: 'Wijs toe wanneer de speler wakker wordt.',
    scriptLinesDutch: ['Rol nog niet onthuld.'],
    scriptLinesEnglish: ['Role not yet revealed.'],
  },
};

/**
 * List of playable secret character cards for deck selection (excludes honorary titles & placeholders)
 */
export const PLAYABLE_SECRET_ROLES: RoleDefinition[] = Object.values(ALL_ROLES).filter(
  (r) => r.id !== 'burgemeester' && r.id !== 'onbekend'
);

export const DECK_PRESETS = [
  {
    name: 'Klassiek Dorp (5-7 spelers)',
    description: '2 Weerwolven, Zienster, Heks + Burgers',
    roles: ['weerwolf', 'weerwolf', 'zienster', 'heks', 'burger', 'burger', 'burger'] as RoleId[],
  },
  {
    name: 'Gebalanceerd Wakkerdam (8-10 spelers)',
    description: '2 Weerwolven, Zienster, Heks, Jager, Cupido, Beschermer + Burgers',
    roles: ['weerwolf', 'weerwolf', 'zienster', 'heks', 'jager', 'cupido', 'beschermer', 'burger', 'burger', 'burger'] as RoleId[],
  },
  {
    name: 'Groot Drama & Chaos (11-15 spelers)',
    description: '3 Weerwolven, Zienster, Heks, Jager, Cupido, Beschermer, Dief, Fluitspeler + Burgers',
    roles: [
      'weerwolf',
      'weerwolf',
      'weerwolf',
      'zienster',
      'heks',
      'jager',
      'cupido',
      'beschermer',
      'dief',
      'dorpsoudste',
      'fluitspeler',
      'burger',
      'burger',
      'burger',
      'burger',
    ] as RoleId[],
  },
];
